### ISSUE TITLE
Question regarding AttrakDiff

### ISSUE THREAD

**Issue by LenaVo** [mantir/reflect#10]
Hey,
I saw your post on stackexchange regarding AttrakDiff evaluation (https://stats.stackexchange.com/questions/251555/calculate-attrakdiff-confidence-rectangle) and I struggle with the exact same problem. I was wondering if you found a way to solve this? 

sorry for posting this as an Issue in your repository, I didn't know where else to ask and you linked a spreadsheet for Lernreflex in the post, so I thought here is most fitting.

Thank you for reading!

**Comment by mantir** [comment]
Hey, sorry, I couldn't find an answer to my question. In the the end I just compared the two app versions.

**Comment by LenaVo** [comment]
Oh, I see.. Thank you for your super quick answer though!
