### ISSUE TITLE
Aktivitäten Kommentare werden auf iOS nicht angezeigt

### ISSUE THREAD

**Issue by EileenL** [mantir/reflect#8]
Ich kann Kommentare zu aktivitäten anlegen, diese werden wohl auch gespeichert und können über Moodle Plattform und Android angesehen werden, sie erscheinen aber nicht bei mir selbst (iOS). Ich sehe auch Mitlernende Kommentare nicht zu den entsprechenden Lernzielen und Aktivitäten

iOS Version des neuesten Standes

**Comment by EileenL** [comment]
Kommentare sind auch bei Neustart der App nicht sichtbar

**Comment by mantir** [comment]
Besteht der Fehler auch nach nochmaligem Login? Ich kann den Fehler bei mir nicht nachvollziehen.

**Comment by EileenL** [comment]
ja da war ein nochmaliges Login nötig. Allerdings ist jetzt die Aktivität gelöscht, so dass ich es nicht mehr kontrollieren kann. 
Für eine andere Aktivität funktioniert es. Der Kommentar ist nach Login weiter sichtbar

**Comment by EileenL** [comment]
und jetzt sehe ich auch die anderen Kommentare. Seltsam. scheint ein Problem mit der speziellen Aktivität gewesen zu sein
